name: Continous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node and dependencies
        uses: ./.github/actions/install

      - name: Typecheck
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit

    steps:
      - uses: actions/checkout@v4

      - name: Install Node and dependencies
        uses: ./.github/actions/install

      - name: Build
        run: npm run build
